language: java
sudo: false
install: true

addons:
  sonarqube:
    organization: "zyra83-github"
    token:
      secure: "Me0wRsfqZvm2EbWPrqVLuVv/+CF+RTZTT7oAk8VxyML3disZfn4mb+QOcvnsBEi9dCLtT6FPGkbX/gySzZMEWDoM3Y69PX8uaYItx70dlixf3X/WT7YqxEe3kTHMNsucT9mR1zG3rPX3rIeoj4kyhH6JJrgxH7hm5a6t1jpWrP37DJ7QHq4vqcG81xoaUyAwOvT7CF61oPdd0tO9yFqup477Y+ezwRF/FKmJcN3xIo/8JWLingsz39RzKG7I/G61OF7ozXdUAqfsTe5NYlL4I2jpdo0jhouYxOVMk984kZ5B3rK7IO7GL4NRXS8GtIfsL0XKYN4fw7G2MgEDWl6J5iMqo1ZmP1yN06hFpZtgwvFzpphElO8MS4reGGvoEqCw0O5lVbyu7rEh6mtJyuekK9jI60gHgMrqDtFOqsAAifFdAjNH14De1tBZPkkn3p7YKhK/455MVeuRcuvTF7fTJX2nZ08OvVeU3+dpUAQz0iJ74SmxJ+EPPuJjFe+Eeks82UkoQDerLjVYMfAJz7shdtFkeD0lZYb2xfCivh2QssqHp5/Ya2Vp9s5NmEQUB/22+JuPidq9rmlbkoVO2hC0j97QWie4gGECyuohYdvFvDaPtVgf2Aop/lp+1+XvLvKu7RSAv+1sa9/EIcrIGyX/29RsQpUXLJr59YQnHoLlnpw="
    github_token:
      secure: "vlQm2xvryDg3erY8BlTrz6W+fU6fO5nTZMB/RRQtIwrZdG813b/JMWekpDcL5VuuzacgJCGH8k/NCGz1BbXbkj3JsPPpETmhGYEeueKFcfBPUJcg6aDySKHcUN9ZhHxtqLXWaATRbN2Ns4SBF5B2/Spl/o5AfUmRkPrydFuCLLWBZomwMAKsazdruejgDu+8KdP7qOHxnVlbICk5V245CEd1vcILyALbePOuL/1HNBQ/Cq/Y4PDmlWx9lnUqPbHlsCrR7qT9CogLAO/e7K13o6j+NwiBDDrM9OIzHTFw48UL/gdeoDI6SFRw1oeX4qQvqBVjhQzktZYTw4/S6As0aAm7iA5ZGIs/qvf3grfGH5SYaKkjwIs8D9HuPfU/NYmPdiz8HNJZJpx41v4uMHxgQCSssHjbASrJuEwkSTtyLeqH62Hwc0qDOzUyI8nlrZXlQvMjpVrfW+VyhfNZm7L7S0CK5QhmkJoysgojCJDYkc2V8AOkGd1HQ1bGBhCNMeTNy9OuoGRi1wCgptUjEROtmX/V6e3ZJFhtFVV66lg9w2ckipbBEbeJ/3rnPiBJyPqPvOSYem2R7UUSaJOHvry50qvc1WEOSFF6XX+LVa1HW0F49Xoxce+yEz/B/N2wPQ5jCGWN1AXDfARG4ogMXubkf6hju2mB57dxRn07E/m0Qy8="

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

before_cache:
  # remove all the artifacts (JAR, ZIP) that are installed in local repo because of mvn deploy
  - rm -rf $HOME/.m2/repository/00BS_Threads
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;
